#!/bin/bash
file=$1
echo 'digraph Deps {'
grep -Ff <(grep "^[[:alnum:]]+" -Eo priv/$1.ctt | grep -Evx "module|import|data") -o $(ls -1 priv/*.ctt | grep -v $file | xargs) | sort -u | sed 's|^priv/||;s|\.ctt||;s|:| -> |;'
echo '}'
