#!/bin/bash
# Script for checking that all files compile

files="binnat function
       iso_example refinement_example
       stream
       coproduct coproduct_noset coproduct_set
       girard puresigma maybenat
       quotient om stream paradox lambek
       collection brunerie trunc fun
       univalence category grothendieck"
skip="lam"

function check_all {
  local parsed=$1
  rm parsed.txt
  for file in $files
  do
   grep "^import $file$" priv/*.ctt
   cubical -b priv/$file.ctt | tee $parsed | grep -vE "0m0|^ *Checking:|^Parsed|File loaded.|^$|cubical, version|shadowed"
  done
}

check_all >(grep Parsed | sed 's|Parsed "priv/||;s|" successfully!||' | sort -u >parsed.txt)
echo Compiled $(cat parsed.txt | wc -l) files of $(ls -1 priv/*.ctt | wc -l) in priv/
echo Skipped files:
join -v2 parsed.txt <(cd priv && ls -1 *.ctt)
