#!/bin/bash
# Script for checking that all files compile

files="retract_unused binnat function
       iso_example refinement_example stream helix
       coproduct coproduct_noset coproduct_set
       girard puresigma maybenat monad pushout vector
       quotient stream paradox lambek
       collection brunerie trunc fun
       univalence category grothendieck"

rm parsed.txt
function compile() {
    file="$1"
    grep "^import $file$" ../priv/*.ctt
    cubical -b ../priv/$file.ctt 
}
export -f compile
parallel compile ::: $files | tee >(grep Parsed | sed 's|Parsed "../priv/||;s|" successfully!||' >>parsed.txt) | grep -vE "0m0|^ *Checking:|^Parsed|File loaded.|^$|cubical, version|shadowed"

echo Compiled $(sort -u parsed.txt | wc -l) files of $(ls -1 priv/*.ctt | wc -l) in priv/
echo Skipped files:
sort -u parsed.txt >distinct.txt
join -v2 distinct.txt <(cd priv && ls -1 *.ctt)
